---

- name: Pull nexus3 docker image
  docker_image:
    name: sonatype/nexus3:{{ docker_nexus3_version }}
    source: pull

- name: Service configuration
  template:
    src: docker-nexus3.j2
    dest: /etc/init.d/docker-nexus3
    mode: ugo+x
  register: docker_nexus3_service
  notify:
    - restart-docker-nexus3
    - systemd-daemon-reload
